name: noorventures
description: "NoorVentures"
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  rename_app:
  change_app_package_name:
  flutter_automation:
  cross_file: ^0.3.4+2
  firebase_app_check:

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar:
  firebase_auth:
  cloud_firestore:
  image_picker: ^1.1.2
  http:
  random_string:
  shared_preferences:
  firebase_storage:
  fluttertoast:
  flutter_launcher_icons:
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - images/logoang.png
    - images/logokaphia.png
    - images/logonoorkitchen.png
    - images/logonoorproperties.png
    - images/logoevent.png
    - images/logonoorventure.png
    - images/logoagro.png
    - images/angp.jpg
    - images/eventp.jpg
    - images/kaphiap.jpg
    - images/kaphiarp.jpg
    - images/prop.jpg
    - images/noorkitchenp.jpg
    - images/userimage.jpg
    - images/NoorVlogo.jpg
    - images/iconphoto.png
    - images/appicon.png
